//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ReporteOcorrenciasMatricula {
    
    private ReporteOcorrenciasMatriculaCredenciaisAcesso credenciaisAcessoField;
    
    private ReporteOcorrenciasMatriculaCabecalho cabecalhoField;
    
    private ReporteOcorrenciasMatriculaOcorrencia[] ocorrenciaField;
    
    private string versaoField;
    
    private string dataVersaoField;
    
    public ReporteOcorrenciasMatricula() {
        this.versaoField = "1";
        this.dataVersaoField = "2014-01-01";
    }
    
    /// <remarks/>
    public ReporteOcorrenciasMatriculaCredenciaisAcesso CredenciaisAcesso {
        get {
            return this.credenciaisAcessoField;
        }
        set {
            this.credenciaisAcessoField = value;
        }
    }
    
    /// <remarks/>
    public ReporteOcorrenciasMatriculaCabecalho Cabecalho {
        get {
            return this.cabecalhoField;
        }
        set {
            this.cabecalhoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ocorrencia")]
    public ReporteOcorrenciasMatriculaOcorrencia[] Ocorrencia {
        get {
            return this.ocorrenciaField;
        }
        set {
            this.ocorrenciaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string Versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string DataVersao {
        get {
            return this.dataVersaoField;
        }
        set {
            this.dataVersaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReporteOcorrenciasMatriculaCredenciaisAcesso {
    
    private string userNameField;
    
    private string passwordField;
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReporteOcorrenciasMatriculaCabecalho {
    
    private string iDReporteField;
    
    private string codigoEstatisticoField;
    
    /// <remarks/>
    public string IDReporte {
        get {
            return this.iDReporteField;
        }
        set {
            this.iDReporteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CodigoEstatistico {
        get {
            return this.codigoEstatisticoField;
        }
        set {
            this.codigoEstatisticoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ReporteOcorrenciasMatriculaOcorrencia {
    
    private string iDOcorrenciaField;
    
    private ReporteOcorrenciasMatriculaOcorrenciaCodigoOperacao codigoOperacaoField;
    
    private string numeroApoliceField;
    
    private string numeroCertificadoProvisorioField;
    
    private string numeroMatriculaField;
    
    private string dataInicioField;
    
    private string horaInicioField;
    
    private string dataFimField;
    
    private string horaFimField;
    
    private string anoConstrucaoField;
    
    private string codigoCategoriaVeiculoField;
    
    private string marcaVeiculoField;
    
    private string modeloVeiculoField;
    
    private string codigoConcelhoCirculacaoField;
    
    private string nomeTomadorSeguroField;
    
    private string numeroIdentificacaoTomadorSeguroField;
    
    private string nIFTomadorSeguroField;
    
    private string moradaTomadorSeguroField;
    
    private string codigoPostalTomadorSeguroField;
    
    /// <remarks/>
    public string IDOcorrencia {
        get {
            return this.iDOcorrenciaField;
        }
        set {
            this.iDOcorrenciaField = value;
        }
    }
    
    /// <remarks/>
    public ReporteOcorrenciasMatriculaOcorrenciaCodigoOperacao CodigoOperacao {
        get {
            return this.codigoOperacaoField;
        }
        set {
            this.codigoOperacaoField = value;
        }
    }
    
    /// <remarks/>
    public string NumeroApolice {
        get {
            return this.numeroApoliceField;
        }
        set {
            this.numeroApoliceField = value;
        }
    }
    
    /// <remarks/>
    public string NumeroCertificadoProvisorio {
        get {
            return this.numeroCertificadoProvisorioField;
        }
        set {
            this.numeroCertificadoProvisorioField = value;
        }
    }
    
    /// <remarks/>
    public string NumeroMatricula {
        get {
            return this.numeroMatriculaField;
        }
        set {
            this.numeroMatriculaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string DataInicio {
        get {
            return this.dataInicioField;
        }
        set {
            this.dataInicioField = value;
        }
    }
    
    /// <remarks/>
    public string HoraInicio {
        get {
            return this.horaInicioField;
        }
        set {
            this.horaInicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string DataFim {
        get {
            return this.dataFimField;
        }
        set {
            this.dataFimField = value;
        }
    }
    
    /// <remarks/>
    public string HoraFim {
        get {
            return this.horaFimField;
        }
        set {
            this.horaFimField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string AnoConstrucao {
        get {
            return this.anoConstrucaoField;
        }
        set {
            this.anoConstrucaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CodigoCategoriaVeiculo {
        get {
            return this.codigoCategoriaVeiculoField;
        }
        set {
            this.codigoCategoriaVeiculoField = value;
        }
    }
    
    /// <remarks/>
    public string MarcaVeiculo {
        get {
            return this.marcaVeiculoField;
        }
        set {
            this.marcaVeiculoField = value;
        }
    }
    
    /// <remarks/>
    public string ModeloVeiculo {
        get {
            return this.modeloVeiculoField;
        }
        set {
            this.modeloVeiculoField = value;
        }
    }
    
    /// <remarks/>
    public string CodigoConcelhoCirculacao {
        get {
            return this.codigoConcelhoCirculacaoField;
        }
        set {
            this.codigoConcelhoCirculacaoField = value;
        }
    }
    
    /// <remarks/>
    public string NomeTomadorSeguro {
        get {
            return this.nomeTomadorSeguroField;
        }
        set {
            this.nomeTomadorSeguroField = value;
        }
    }
    
    /// <remarks/>
    public string NumeroIdentificacaoTomadorSeguro {
        get {
            return this.numeroIdentificacaoTomadorSeguroField;
        }
        set {
            this.numeroIdentificacaoTomadorSeguroField = value;
        }
    }
    
    /// <remarks/>
    public string NIFTomadorSeguro {
        get {
            return this.nIFTomadorSeguroField;
        }
        set {
            this.nIFTomadorSeguroField = value;
        }
    }
    
    /// <remarks/>
    public string MoradaTomadorSeguro {
        get {
            return this.moradaTomadorSeguroField;
        }
        set {
            this.moradaTomadorSeguroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CodigoPostalTomadorSeguro {
        get {
            return this.codigoPostalTomadorSeguroField;
        }
        set {
            this.codigoPostalTomadorSeguroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum ReporteOcorrenciasMatriculaOcorrenciaCodigoOperacao {
    
    /// <remarks/>
    C,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    A,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ReporteOcorrenciasMatriculaResposta {
    
    private string idField;
    
    private string codigoEstatisticoField;
    
    private bool indicadorSucessoReporteField;
    
    private string descricaoComplementarErroField;
    
    private string versaoField;
    
    private string dataVersaoField;
    
    public ReporteOcorrenciasMatriculaResposta() {
        this.versaoField = "1";
        this.dataVersaoField = "2014-01-01";
    }
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CodigoEstatistico {
        get {
            return this.codigoEstatisticoField;
        }
        set {
            this.codigoEstatisticoField = value;
        }
    }
    
    /// <remarks/>
    public bool IndicadorSucessoReporte {
        get {
            return this.indicadorSucessoReporteField;
        }
        set {
            this.indicadorSucessoReporteField = value;
        }
    }
    
    /// <remarks/>
    public string DescricaoComplementarErro {
        get {
            return this.descricaoComplementarErroField;
        }
        set {
            this.descricaoComplementarErroField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string Versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string DataVersao {
        get {
            return this.dataVersaoField;
        }
        set {
            this.dataVersaoField = value;
        }
    }
}
